// Complete National NERDC Scheme of Work Dataset (Exactly Week 1 to Week 10 for all terms)
const CURRICULUM_DATA = {
    Mathematics: {
        'JSS 1': {
            'Term 1': [
                { week: 'Week 1', topic: 'Whole Numbers: Large Numbers', objectives: ['Write whole numbers in words and figures up to trillions', 'Determine the place value of any digit in a large number', 'Convert numbers to Roman numerals and vice-versa'] },
                { week: 'Week 2', topic: 'Whole Numbers: Operations', objectives: ['Perform addition and subtraction on very large numbers', 'Perform multiplication and division on large numbers', 'Solve quantitative reasoning problems involving whole numbers'] },
                { week: 'Week 3', topic: 'Prime Factors & Factorization', objectives: ['Identify prime numbers and composite numbers', 'Write numbers as products of prime factors using factor tree or division methods', 'Apply prime factors in daily problem solving'] },
                { week: 'Week 4', topic: 'HCF and LCM', objectives: ['Find the Highest Common Factor (HCF) of two or three numbers', 'Find the Lowest Common Multiple (LCM) of numbers', 'Solve word problems involving HCF and LCM in real life'] },
                { week: 'Week 5', topic: 'Fractions: Types & Conversions', objectives: ['Distinguish between proper, improper, and mixed fractions', 'Convert fractions to decimals and percentages', 'Convert decimals and percentages back to fractions'] },
                { week: 'Week 6', topic: 'Fractions Operations', objectives: ['Perform addition and subtraction on common fractions', 'Perform multiplication and division on common fractions', 'Apply BODMAS rule to solve compound fraction expressions'] },
                { week: 'Week 7', topic: 'Decimals and Percentages', objectives: ['Perform multiplication and division on decimal numbers', 'Calculate percentages of various quantities', 'Solve word problems involving simple percentage increases or decreases'] },
                { week: 'Week 8', topic: 'Estimation', objectives: ['Estimate results of sums, products, differences, and quotients', 'Round off numbers to the nearest tens, hundreds, and thousands', 'Evaluate the accuracy of estimated answers in shopping scenarios'] },
                { week: 'Week 9', topic: 'Approximation', objectives: ['Round numbers to a specified number of decimal places', 'Round numbers to a specified number of significant figures', 'Understand the concept of rounding up and rounding down'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review all topics taught in Term 1', 'Practice with past terminal examination questions', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Number Bases (Introduction)', objectives: ['Understand the concept of place value in base ten system', 'Introduce other number bases (base 2, base 5, base 8)', 'Distinguish between binary and denary systems'] },
                { week: 'Week 2', topic: 'Number Bases (Conversion)', objectives: ['Convert numbers from base ten (denary) to base two (binary)', 'Convert binary numbers back to base ten', 'Apply base conversion to simple code designs'] },
                { week: 'Week 3', topic: 'Binary Arithmetic', objectives: ['Perform simple addition of binary numbers', 'Perform simple subtraction of binary numbers', 'Verify binary operation results by converting to base ten'] },
                { week: 'Week 4', topic: 'Algebra Fundamentals: Terminology', objectives: ['Define variables, constants, coefficients, and algebraic terms', 'Distinguish between expressions and equations', 'Identify coefficients of variables in given expressions'] },
                { week: 'Week 5', topic: 'Algebraic Expressions', objectives: ['Translate word problems into algebraic symbols', 'Simplify simple algebraic expressions by grouping like terms', 'Perform basic addition and subtraction of algebraic terms'] },
                { week: 'Week 6', topic: 'Simplifying Algebraic Brackets', objectives: ['Expand simple algebraic brackets containing positive signs', 'Expand brackets containing negative signs', 'Evaluate expressions by substituting given values for variables'] },
                { week: 'Week 7', topic: 'Directed Numbers: Number Line', objectives: ['Represent positive and negative integers on a number line', 'Compare directed numbers using inequality symbols (< and >)', 'Locate positions of numbers relative to zero'] },
                { week: 'Week 8', topic: 'Directed Numbers: Operations', objectives: ['Perform addition and subtraction of directed numbers using a number line', 'Multiply and divide directed numbers successfully', 'Use directed numbers in simple bracket expansions'] },
                { week: 'Week 9', topic: 'Directed Numbers: Daily Applications', objectives: ['Apply directed numbers in daily calculations (profit/loss, altitude, depth)', 'Solve temperature change problems using negative integers', 'Understand credits and debits as directed integers'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review all algebraic and arithmetic topics taught in Term 2', 'Solve sample questions on directed numbers and bases', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Plane Shapes: Properties', objectives: ['Identify properties of triangles, rectangles, and squares', 'Identify properties of circles, parallelograms, and trapeziums', 'Distinguish between regular and irregular polygons'] },
                { week: 'Week 2', topic: 'Perimeter of Plane Shapes', objectives: ['Calculate the perimeter of triangles, rectangles, and squares', 'Calculate the perimeter of composite plane shapes', 'Solve word problems involving lengths of fences or boundaries'] },
                { week: 'Week 3', topic: 'Area of Plane Shapes', objectives: ['State formulas for calculating area of triangles and quadrilaterals', 'Calculate area of squares, rectangles, and triangles', 'Solve practical problems on tiling or painting surfaces'] },
                { week: 'Week 4', topic: 'The Circle: Circumference & Area', objectives: ['Identify parts of a circle (radius, diameter, circumference, chord)', 'Calculate the circumference of a circle using C = 2πr', 'Calculate the area of a circle using A = πr^2'] },
                { week: 'Week 5', topic: 'Angles: Types & Measurement', objectives: ['Identify types of angles (acute, obtuse, right, straight, reflex)', 'Measure angles accurately using a protractor', 'Solve simple problems involving angles at a point'] },
                { week: 'Week 6', topic: 'Angles on a Straight Line & Vertically Opposite', objectives: ['Apply the rule that angles on a straight line sum to 180 degrees', 'Apply the rule that angles around a point sum to 360 degrees', 'Identify and calculate vertically opposite angles'] },
                { week: 'Week 7', topic: 'Geometric Construction: Basics', objectives: ['Construct perpendicular lines and parallel lines using ruler and set square', 'Bisect a given line segment accurately', 'Bisect any given angle using a pair of compasses'] },
                { week: 'Week 8', topic: 'Geometric Construction: Angles', objectives: ['Construct angles of 90 degrees and 60 degrees', 'Construct angles of 45, 30, and 15 degrees by bisection', 'Construct simple triangles given three sides or two sides and an angle'] },
                { week: 'Week 9', topic: 'Measures of Average', objectives: ['Calculate the arithmetic Mean of a set of ungrouped data', 'Find the Median (middle value) of a data set', 'Identify the Mode (most frequent value) in data'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review all geometry and statistics topics taught in Term 3', 'Complete geometric drawing practical revisions', 'Complete the end-of-term mathematics examination'] }
            ]
        },
        'JSS 2': {
            'Term 1': [
                { week: 'Week 1', topic: 'Directed Numbers: Multiplication & Division', objectives: ['Multiply and divide directed numbers successfully', 'Solve combined operations involving directed integers', 'Understand signs rule (+ x - = -, - x - = +)'] },
                { week: 'Week 2', topic: 'Directed Numbers: Brackets Expansion', objectives: ['Use directed numbers in simple brackets expansion', 'Simplify terms after expanding brackets', 'Solve word problems involving positive and negative numbers'] },
                { week: 'Week 3', topic: 'Ratios and Percentages', objectives: ['Simplify ratios and divide quantities in given ratios', 'Increase or decrease quantities by percentages', 'Solve word problems involving ratios in business and science'] },
                { week: 'Week 4', topic: 'Proportions: Direct Proportion', objectives: ['Explain the concept of direct proportion', 'Solve direct proportion problems using unitary or ratio methods', 'Plot graphs representing direct proportional relationships'] },
                { week: 'Week 5', topic: 'Proportions: Inverse Proportion', objectives: ['Explain the concept of inverse proportion', 'Solve inverse proportion problems', 'Apply proportions to real-life situations like labor and time'] },
                { week: 'Week 6', topic: 'Financial Arithmetic: Simple Interest', objectives: ['Calculate Simple Interest using the formula I = PRT/100', 'Determine Principal (P), Rate (R), or Time (T) from the formula', 'Solve practical investment and loan calculations'] },
                { week: 'Week 7', topic: 'Financial Arithmetic: Compound Interest', objectives: ['Explain the difference between simple and compound interest', 'Calculate compound interest step-by-step for up to 3 years', 'Understand financial inflation and depreciation concepts'] },
                { week: 'Week 8', topic: 'Household Finances: Profit & Loss', objectives: ['Calculate cost price, selling price, profit, and loss', 'Calculate percentage profit and percentage loss', 'Evaluate discount and commission in business transactions'] },
                { week: 'Week 9', topic: 'Household Finances: Rates & Bills', objectives: ['Compute electricity, water, and telephone bills based on rates', 'Understand local government rates, tenement rates, and taxation', 'Construct household budget estimations'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review ratios, proportions, simple interest, and commercial mathematics', 'Practice terminal examination question formats', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Linear Equations: Basic Solutions', objectives: ['Solve simple linear equations in one variable', 'Understand balanced scale principles in solving equations', 'Solve equations containing brackets or fractional coefficients'], dbTopicMatch: 'linear equations' },
                { week: 'Week 2', topic: 'Linear Equations: Word Problems', objectives: ['Translate everyday word problems into linear equations', 'Solve word problems relating to ages, numbers, and geometry', 'Verify the solutions of equations by substitution'] },
                { week: 'Week 3', topic: 'Linear Equations: Graphing', objectives: ['Construct tables of values for simple linear equations', 'Plot coordinates on a Cartesian plane', 'Draw straight-line graphs and identify the gradient'] },
                { week: 'Week 4', topic: 'Linear Inequalities: Introduction', objectives: ['Introduce inequality symbols (<, >, <=, >=)', 'Solve simple linear inequalities in one variable', 'State the effect of multiplying or dividing by negative numbers'] },
                { week: 'Week 5', topic: 'Linear Inequalities: Graphing', objectives: ['Represent inequality solutions on a number line', 'Solve combined inequalities and show range solutions', 'Apply inequalities to real-world boundary problems'] },
                { week: 'Week 6', topic: 'Pythagoras Theorem: Introduction', objectives: ['State the Pythagoras Theorem (a^2 + b^2 = c^2)', 'Identify parts of a right-angled triangle (hypotenuse, adjacent, opposite)', 'Prove the theorem using area methods'] },
                { week: 'Week 7', topic: 'Pythagoras Theorem: Calculations', objectives: ['Calculate the hypotenuse given two other sides', 'Calculate any other side given the hypotenuse and one side', 'Solve problems involving decimal values'] },
                { week: 'Week 8', topic: 'Pythagoras Theorem: Applications', objectives: ['Apply Pythagoras theorem to solve height and distance problems', 'Determine diagonal lengths of rectangles and squares', 'Solve ladder and wall alignment word problems'] },
                { week: 'Week 9', topic: 'Algebraic Expressions: Expansion', objectives: ['Perform expansion of single algebraic expressions', 'Multiply binomial terms and group like terms', 'Simplify expressions with multiple variables'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review linear equations, inequalities, Pythagoras theorem, and algebra', 'Verify and solve mock tests', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Surface Area of Solid Shapes', objectives: ['Calculate the surface area of cubes and cuboids', 'Calculate the surface area of cylinders', 'Solve word problems involving painting or wrapping solid objects'] },
                { week: 'Week 2', topic: 'Volumes of Prisms & Cylinders', objectives: ['Calculate the volume of cubes and cuboids', 'Calculate the volume of cylinders', 'Solve word problems involving capacities of water tanks and pipes'] },
                { week: 'Week 3', topic: 'Volumes of Pyramids & Cones', objectives: ['State formulas for volumes of pyramids and cones', 'Calculate volumes of cones and right pyramids', 'Compare volumes of cylinders and cones with same dimensions'] },
                { week: 'Week 4', topic: 'Data Presentation: Frequency Tables', objectives: ['Collect data and construct frequency distribution tables', 'Differentiate between discrete and continuous data', 'Identify class intervals and tallies'] },
                { week: 'Week 5', topic: 'Data Presentation: Bar & Pie Charts', objectives: ['Construct bar charts representing statistical data', 'Calculate sectors in degrees for pie charts', 'Draw and interpret pie charts accurately'] },
                { week: 'Week 6', topic: 'Probability: Basics', objectives: ['Define probability and understand the scale from 0 to 1', 'Distinguish between certain, impossible, and likely events', 'Express probability as fractions, decimals, or percentages'] },
                { week: 'Week 7', topic: 'Theoretical Probability', objectives: ['Calculate the probability of simple experimental events', 'Solve problems involving throwing a single die', 'Solve problems involving tossing a coin'] },
                { week: 'Week 8', topic: 'Probability: Complex Scenarios', objectives: ['Solve probability games of chance involving playing cards', 'Calculate probabilities of picking colored balls from a bag', 'Solve combined simple probability questions'] },
                { week: 'Week 9', topic: 'Statistical Graphs', objectives: ['Construct and interpret line graphs', 'Plot and analyze simple histograms', 'Evaluate trends in statistical records'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review all solid shape mensuration, data charts, and probability', 'Resolve previous exam scripts', 'Complete the end-of-term mathematics examination'] }
            ]
        },
        'JSS 3': {
            'Term 1': [
                { week: 'Week 1', topic: 'Binary Operations: Addition', objectives: ['Perform addition of numbers in base 2 (binary)', 'Understand binary arithmetic carry-over principles', 'Convert binary addition results back to base 10'] },
                { week: 'Week 2', topic: 'Binary Operations: Multi-Bases', objectives: ['Perform subtraction of binary numbers', 'Perform multiplication of binary numbers', 'Solve arithmetic operations in base 5 and base 8'] },
                { week: 'Week 3', topic: 'Base Equations', objectives: ['Solve simple algebraic equations involving number bases', 'Find the unknown base "x" in a base equation', 'Apply base conversion principles to solve algebraic variables'] },
                { week: 'Week 4', topic: 'Rational & Irrational Numbers', objectives: ['Distinguish between rational and irrational numbers', 'Define surds as irrational roots', 'Identify repeating and non-repeating decimals'] },
                { week: 'Week 5', topic: 'Indices: Basic Laws', objectives: ['State the laws of indices (multiplication, division, and power laws)', 'Apply basic laws of indices to simplify algebraic terms', 'Evaluate numerical terms raised to positive index powers'] },
                { week: 'Week 6', topic: 'Indices: Zero & Negative Powers', objectives: ['Understand the zero index law (a^0 = 1)', 'State and apply the negative index law', 'State and apply the fractional index law'] },
                { week: 'Week 7', topic: 'Expansion of Algebraic Expressions', objectives: ['Expand expressions of the form (a+b)(c+d)', 'Expand expressions containing multiple variables', 'Simplify expanded expressions by grouping like terms'] },
                { week: 'Week 8', topic: 'Factorization of Expressions', objectives: ['Factorize simple algebraic expressions by taking out common factors', 'Factorize expressions by grouping four terms', 'Understand factors of quadratic binomials'] },
                { week: 'Week 9', topic: 'Expansion of Binomial Squares', objectives: ['Apply binomial expansion to expand squares like (a+b)^2 and (a-b)^2', 'Understand the difference of two squares identity', 'Factorize quadratic expressions using difference of two squares'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review binary bases, indices, expansion, and factorization', 'Complete quantitative reasoning mock exercises', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Simultaneous Equations: Elimination', objectives: ['Define simultaneous linear equations in two variables', 'Solve simultaneous equations using the elimination method', 'Verify algebraic solutions by back-substitution'] },
                { week: 'Week 2', topic: 'Simultaneous Equations: Substitution', objectives: ['Solve simultaneous equations using the substitution method', 'Formulate simultaneous equations from real-life scenarios', 'Compare efficiency of elimination vs. substitution methods'] },
                { week: 'Week 3', topic: 'Simultaneous Equations: Graphical', objectives: ['Construct tables of values for two linear equations', 'Plot both lines on the same coordinate grid', 'Locate the point of intersection as the simultaneous solution'] },
                { week: 'Week 4', topic: 'Quadratic Equations: Factorization', objectives: ['Solve quadratic equations of the form ax^2 + bx + c = 0 by factorization', 'Find the roots of quadratic equations with simple integer coefficients', 'Apply quadratic factorization to geometric problems'] },
                { week: 'Week 5', topic: 'Quadratic Equations: Word Problems', objectives: ['Translate everyday word problems into quadratic equations', 'Formulate and solve quadratic equations relating to areas and ages', 'Select the realistic root in physical contexts'] },
                { week: 'Week 6', topic: 'Direct Variation', objectives: ['Formulate equations for Direct variations (y = kx)', 'Calculate the constant of variation "k"', 'Solve complex word problems involving direct relationships'] },
                { week: 'Week 7', topic: 'Inverse Variation', objectives: ['Formulate equations for Inverse variations (y = k/x)', 'Compute the constant of proportionality "k"', 'Solve inverse variation word problems (e.g. speed and time)'] },
                { week: 'Week 8', topic: 'Joint & Partial Variations', objectives: ['Formulate equations for Joint variation (y = kxz)', 'Understand the concept and equations of Partial variation', 'Solve combined variation word problems'] },
                { week: 'Week 9', topic: 'Trigonometric Ratios: Introduction', objectives: ['Define Sine, Cosine, and Tangent using right-angled triangles', 'Remember SOHCAHTOA definitions', 'Find angles and sides using trigonometric tables or calculators'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review simultaneous equations, quadratics, variations, and trig ratios', 'Practice JSSCE mock exam booklets', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Mensuration: The Sphere', objectives: ['State formulas for surface area and volume of a sphere', 'Calculate the surface area of a sphere given radius', 'Calculate the volume of a sphere and hemisphere'] },
                { week: 'Week 2', topic: 'Mensuration: The Cone', objectives: ['State formulas for curved surface area, total surface area, and volume of a cone', 'Calculate curved surface area and total surface area of a cone', 'Calculate the volume of a cone using height and radius'] },
                { week: 'Week 3', topic: 'Mensuration of Solid Shapes', objectives: ['Solve compound mensuration problems (e.g., cylinder topped by a cone)', 'Calculate surface area and volume of composite solids', 'Solve practical liquid volume displacement problems'] },
                { week: 'Week 4', topic: 'Angles of Elevation & Depression', objectives: ['Define angle of elevation and angle of depression', 'Represent elevation and depression scenarios using right-angled triangles', 'Solve simple heights and distances problems'] },
                { week: 'Week 5', topic: 'Elevation & Depression: Complex Problems', objectives: ['Solve multi-step height problems using trigonometric ratios', 'Apply angles of depression in coastal or cliff surveying problems', 'Verify drawn scale models of elevation problems'] },
                { week: 'Week 6', topic: 'Coordinate Geometry: Midpoint', objectives: ['Plot coordinates on a Cartesian plane', 'Find the midpoint of a line segment connecting two points', 'Understand midpoint coordinate formula'] },
                { week: 'Week 7', topic: 'Statistics: Grouped Data', objectives: ['Understand the difference between ungrouped and grouped data', 'Calculate the arithmetic mean of a set of grouped data', 'Find the modal class and median class of grouped frequency tables'] },
                { week: 'Week 8', topic: 'Statistics: Ogive Curves', objectives: ['Calculate cumulative frequencies in grouped tables', 'Plot cumulative frequency graphs (Ogive)', 'Read quartiles and median values from an Ogive curve'] },
                { week: 'Week 9', topic: 'General Revisions', objectives: ['Review all Mathematics topics from JSS 1, JSS 2, and JSS 3', 'Complete comprehensive speed practice tests', 'Conduct mock exam review workshops'] },
                { week: 'Week 10', topic: 'JSSCE Final Examinations', objectives: ['Sit for the Junior Secondary Certificate Examinations', 'Complete practical and theory booklets successfully', 'Evaluate final mathematics mastery metrics'] }
            ]
        },
        'SS 1': {
            'Term 1': [
                { week: 'Week 1', topic: 'Number Bases Expansion', objectives: ['Convert fractional numbers to base 10 from other bases', 'Solve complex algebraic equations involving number bases', 'Understand computer data representation using hexadecimal and octal'] },
                { week: 'Week 2', topic: 'Modular Arithmetic: Operations', objectives: ['Describe and perform addition, subtraction, and multiplication in modular arithmetic', 'Apply modular arithmetic to calendar and clock systems', 'Understand residue classes and modular systems'] },
                { week: 'Week 3', topic: 'Modular Arithmetic: Equations', objectives: ['Find modular inverses for various integers', 'Solve simple linear modular equations', 'Apply modular operations to security codes and encryption'] },
                { week: 'Week 4', topic: 'Indices Laws', objectives: ['Apply laws of indices including fractional and negative indices', 'Simplify complex exponential fractions', 'Apply index rules to scientific notation conversions'] },
                { week: 'Week 5', topic: 'Exponential Equations', objectives: ['Solve exponential equations using index laws', 'Solve equations that reduce to quadratic forms', 'Verify index equation roots by substitution'] },
                { week: 'Week 6', topic: 'Surds: Addition & Subtraction', objectives: ['Define surds and distinguish them from rational indices', 'Simplify surds to standard form (a√b)', 'Perform addition and subtraction on similar surds'] },
                { week: 'Week 7', topic: 'Surds: Rationalization', objectives: ['Perform multiplication and division of surds', 'Rationalize simple surd denominators', 'Rationalize binomial surd denominators using conjugates'] },
                { week: 'Week 8', topic: 'Logarithms: Rules & Tables', objectives: ['State the laws of logarithms', 'Calculate characteristics and mantissa for numbers greater than 1', 'Perform multiplication and division using logarithmic tables'] },
                { week: 'Week 9', topic: 'Logarithmic Equations', objectives: ['Solve equations involving logarithmic terms', 'Convert equations between exponential and logarithmic forms', 'Verify logarithmic solutions by checks'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review bases, modular arithmetic, indices, surds, and logarithms', 'Conduct terminal practice testing sessions', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Set Theory: Introduction', objectives: ['Define sets, elements, universal set, empty set, subsets, and complement', 'Use correct set notation symbols (∈, ⊂, ∅, U)', 'Differentiate between finite and infinite sets'] },
                { week: 'Week 2', topic: 'Set Operations & Venn Diagrams', objectives: ['Perform union, intersection, and difference of sets', 'Represent set operations using two-set Venn diagrams', 'Shade appropriate regions in Venn diagrams representing logical sets'] },
                { week: 'Week 3', topic: 'Set Theory: Two-Set Word Problems', objectives: ['Formulate mathematical equations from two-set word problems', 'Solve two-set word problems using Venn diagrams', 'Evaluate unknown intersection or subset counts'] },
                { week: 'Week 4', topic: 'Set Theory: Three-Set Word Problems', objectives: ['Formulate equations for three-set scenarios', 'Solve three-set word problems using Venn diagrams', 'Apply set theory to analyze poll and survey outcomes'] },
                { week: 'Week 5', topic: 'Quadratic Equations: Completion of Square', objectives: ['Solve quadratic equations by completing the square', 'Solve equations containing fractional coefficients', 'Understand visual representations of completing the square'] },
                { week: 'Week 6', topic: 'Quadratic Equations: Formula Method', objectives: ['Derive the general quadratic formula (Al-Khwarizmi formula)', 'Apply the quadratic formula to solve quadratic equations', 'Handle decimal or irrational roots accurately'] },
                { week: 'Week 7', topic: 'The Discriminant & Nature of Roots', objectives: ['State the discriminant formula (D = b^2 - 4ac)', 'Determine the nature of roots (real and distinct, real and equal, complex)', 'Solve for variables given root constraints'] },
                { week: 'Week 8', topic: 'Quadratic Equations: Word Problems', objectives: ['Translate complex word problems into quadratic equations', 'Solve and choose realistic roots in physical problems', 'Solve combined quadratic-linear word problems'] },
                { week: 'Week 9', topic: 'Logical Reasoning: Statements', objectives: ['Define simple and compound logical statements', 'Understand logical operators: conjunction, disjunction, implication, and equivalence', 'Construct truth tables for simple compound statements'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review sets, quadratic equations, and logical reasoning', 'Complete mock theory booklet answers', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Trigonometric Ratios: All Quadrants', objectives: ['Extend trigonometric ratios to obtuse and reflex angles', 'Understand the CAST rule and quadrant boundaries', 'Find trigonometric ratios of angles up to 360 degrees'] },
                { week: 'Week 2', topic: 'The Sine Rule', objectives: ['State the Sine Rule (a/sin A = b/sin B = c/sin C)', 'Prove the Sine Rule for acute-angled triangles', 'Apply the Sine Rule to calculate sides and angles of non-right-angled triangles'] },
                { week: 'Week 3', topic: 'The Cosine Rule', objectives: ['State the Cosine Rule (a^2 = b^2 + c^2 - 2bc cos A)', 'Prove the Cosine Rule for acute-angled triangles', 'Apply the Cosine Rule to find side lengths and angle sizes'] },
                { week: 'Week 4', topic: 'Coordinate Geometry: Distance', objectives: ['Calculate the distance between two points on the Cartesian plane', 'Find the coordinates of the midpoint of a line segment', 'Solve simple coordinate geometry geometric problems'] },
                { week: 'Week 5', topic: 'Coordinate Geometry: Gradient', objectives: ['Calculate the gradient/slope (m) of a straight line connecting two points', 'Understand positive, negative, zero, and undefined slopes', 'Apply gradient concepts to real-world rate of change graphs'] },
                { week: 'Week 6', topic: 'Straight Line Equations: Gradient-Intercept', objectives: ['Write the equation of a straight line in gradient-intercept form (y = mx + c)', 'Find the y-intercept and x-intercept of straight lines', 'Graph straight lines from their equations'] },
                { week: 'Week 7', topic: 'Straight Line Equations: Point-Slope', objectives: ['Write line equations using point-slope and two-point forms', 'Understand parallel line gradient relationships (m1 = m2)', 'Understand perpendicular line gradient relationships (m1 * m2 = -1)'] },
                { week: 'Week 8', topic: 'Mensuration: Circles & Sectors', objectives: ['Calculate the arc length of a circle', 'Calculate the area of a sector of a circle', 'Calculate the area of a segment of a circle'] },
                { week: 'Week 9', topic: 'Mensuration: Prisms & Pyramids', objectives: ['Calculate the total surface area and volume of prisms and cylinders', 'Calculate the total surface area and volume of pyramids and cones', 'Solve practical liquid volume capacity conversion problems'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review all trigonometry, coordinate geometry, and solid shape mensuration', 'Practice drawing lines and bisecting sectors', 'Complete the end-of-term mathematics examination'] }
            ]
        },
        'SS 2': {
            'Term 1': [
                { week: 'Week 1', topic: 'Logarithms of Numbers < 1', objectives: ['Understand negative characteristics in logs of numbers less than 1', 'Represent logarithms with bar notation (e.g. 1̄.45)', 'Read log tables for decimal fractional values'] },
                { week: 'Week 2', topic: 'Logarithmic Calculations', objectives: ['Perform multiplication and division on numbers less than 1 using log tables', 'Calculate powers and roots of decimal fractions using logs', 'Solve logarithmic algebraic equations'] },
                { week: 'Week 3', topic: 'Arithmetic Progression: nth Term', objectives: ['Define sequence and series', 'Derive the formula for the nth term of an Arithmetic Progression (AP)', 'Find the first term, common difference, or number of terms of an AP'] },
                { week: 'Week 4', topic: 'Arithmetic Progression: Summation', objectives: ['Derive the formula for the sum of the first n terms of an AP', 'Calculate the sum of arithmetic progression series', 'Solve word problems involving AP series in salaries and brickwork'] },
                { week: 'Week 5', topic: 'Geometric Progression: nth Term', objectives: ['Define Geometric Progression (GP) and common ratio', 'Derive the formula for the nth term of a GP', 'Find the first term, common ratio, or number of terms of a GP'] },
                { week: 'Week 6', topic: 'Geometric Progression: Summation', objectives: ['Derive the formula for the sum of the first n terms of a GP', 'Calculate the sum of geometric progression series', 'Solve word problems involving GP in bacteria growth and biology'] },
                { week: 'Week 7', topic: 'GP: Sum to Infinity', objectives: ['Understand the concept of a converging geometric series', 'Derive and apply the formula for the sum to infinity of a GP', 'Convert recurring decimals to fractions using GP'] },
                { week: 'Week 8', topic: 'Linear Inequalities in 2 Variables', objectives: ['Graph linear inequalities on a Cartesian plane', 'Differentiate between solid boundaries (<=, >=) and dashed boundaries (<, >)', 'Identify feasible regions bounded by systems of linear inequalities'] },
                { week: 'Week 9', topic: 'Linear Programming', objectives: ['Formulate linear programming models from resource limits', 'Graphically solve linear programming objective functions', 'Identify optimum points at feasible region vertices'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review logarithms, sequences (AP/GP), inequalities, and linear programming', 'Practice drawing regions and plotting coordinates', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Algebraic Fractions: Simplification', objectives: ['Simplify algebraic fractions by factorization', 'Identify values for which algebraic fractions are undefined', 'Factorize quadratic terms in fractional numerators and denominators'] },
                { week: 'Week 2', topic: 'Operations on Algebraic Fractions', objectives: ['Perform addition and subtraction on algebraic fractions', 'Perform multiplication and division on algebraic fractions', 'Simplify complex fractional algebraic expressions'] },
                { week: 'Week 3', topic: 'Equations with Algebraic Fractions', objectives: ['Solve linear equations containing algebraic fractions', 'Solve fractional equations that reduce to quadratic forms', 'Verify algebraic fraction equation solutions by checks'] },
                { week: 'Week 4', topic: 'Simultaneous Equations: Linear-Quadratic', objectives: ['Identify equations containing one linear and one quadratic expression', 'Solve simultaneous equations using substitution methods', 'Interpret graphical intersections of lines and curves'] },
                { week: 'Week 5', topic: 'Linear-Quadratic Word Problems', objectives: ['Translate complex real-world word problems into linear-quadratic systems', 'Solve and choose realistic solutions in physical problems', 'Solve combined coordinate intersection equations'] },
                { week: 'Week 6', topic: 'Circle Geometry: Chords', objectives: ['State and prove theorems relating to chords and perpendiculars from the center', 'Calculate chord lengths and distance of chords from circle centers', 'Solve overlapping chord calculation questions'] },
                { week: 'Week 7', topic: 'Circle Geometry: Cyclic Quadrilaterals', objectives: ['Prove circle theorems relating to angles in the same segment', 'Prove that opposite angles of a cyclic quadrilateral sum to 180 degrees', 'Calculate angles in cyclic circles'] },
                { week: 'Week 8', topic: 'Circle Geometry: Tangents', objectives: ['Prove theorems relating to tangents and radii at points of contact', 'Prove alternate segment theorems', 'Calculate angles and lengths involving circle tangents'] },
                { week: 'Week 9', topic: 'Circle Geometry Proofs', objectives: ['Construct logical geometric proofs using geometric axioms', 'Solve compound circle geometry angles problems', 'Construct circle tangents accurately'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review algebraic fractions, simultaneous systems, and circle geometry theorems', 'Execute practice theorem proof booklets', 'Complete the end-of-term mathematics examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Bearings: Introduction', objectives: ['Represent directions using 3-figure bearings (000° to 360°)', 'Represent directions using compass bearings (N45°E, S30°W)', 'Convert compass bearings to 3-figure bearings and vice-versa'] },
                { week: 'Week 2', topic: 'Bearings and Distances: Problems', objectives: ['Represent navigation and surveying problems using scale drawings', 'Calculate distances and bearings between two points using sine/cosine rules', 'Solve real-world bearing word problems'] },
                { week: 'Week 3', topic: 'Probability: Permutations', objectives: ['Understand the concept of factorial notation (n!)', 'Define permutations as arrangements', 'Solve simple permutation problems'] },
                { week: 'Week 4', topic: 'Probability: Combinations', objectives: ['Define combinations as selections', 'Apply combination formulas in solving selection groups', 'Differentiate between permutations and combinations'] },
                { week: 'Week 5', topic: 'Probability Laws', objectives: ['State the addition law of probability (OR rule)', 'State the multiplication law of probability (AND rule)', 'Solve probability problems involving mutually exclusive and independent events'] },
                { week: 'Week 6', topic: 'Conditional Probability', objectives: ['Understand the concept of conditional probability', 'Construct and interpret probability tree diagrams', 'Solve probability questions without replacement'] },
                { week: 'Week 7', topic: 'Statistics: Measures of Dispersion', objectives: ['Calculate the range and mean deviation of grouped data', 'Calculate the variance of grouped data', 'Calculate the Standard Deviation of grouped data'] },
                { week: 'Week 8', topic: 'Statistical Charts', objectives: ['Construct histograms and frequency polygons representing grouped data', 'Construct and read cumulative frequency curves (Ogive)', 'Identify quartiles and interquartile ranges'] },
                { week: 'Week 9', topic: 'Trigonometric Graphs', objectives: ['Construct tables of values for y = sin x and y = cos x', 'Plot sine and cosine graphs on Cartesian grids', 'Determine amplitudes, periods, and phase shifts from graphs'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review bearings, probability, statistics, and trig graphs', 'Complete terminal exam revision papers', 'Complete the end-of-term mathematics examination'] }
            ]
        },
        'SS 3': {
            'Term 1': [
                { week: 'Week 1', topic: 'Matrices: Introduction', objectives: ['Define matrices, order/dimensions of matrices, and types of matrices', 'Perform addition and subtraction of matrices', 'Perform scalar multiplication on matrices'] },
                { week: 'Week 2', topic: 'Matrix Multiplication', objectives: ['Understand condition for matrix multiplication', 'Perform multiplication of 2x2 and 3x3 matrices', 'State properties of matrix multiplication'] },
                { week: 'Week 3', topic: 'Determinants & Inverse', objectives: ['Calculate the determinant of a 2x2 matrix', 'Find the transpose and adjoint of a 2x2 matrix', 'Calculate the inverse of a 2x2 matrix'] },
                { week: 'Week 4', topic: 'Simultaneous Equations: Matrices', objectives: ['Represent simultaneous equations in matrix form (AX = B)', 'Solve simultaneous equations in two variables using matrix inverse method', 'Solve simultaneous equations using Cramer\'s rule'] },
                { week: 'Week 5', topic: 'Vectors in a Plane: Component Form', objectives: ['Represent vectors in component form (xi + yj)', 'Calculate the magnitude/length of a vector', 'Perform addition and subtraction of vectors in component forms'] },
                { week: 'Week 6', topic: 'Vectors in a Plane: Dot Product', objectives: ['Calculate the scalar product (dot product) of two vectors', 'Calculate the angle between two vectors using dot products', 'Understand conditions for parallel and perpendicular vectors'] },
                { week: 'Week 7', topic: 'Coordinate Geometry of Circle', objectives: ['Find the equation of a circle given center (h, k) and radius r', 'Convert standard circle equations to general forms', 'Find the center and radius of a circle from its general equation'] },
                { week: 'Week 8', topic: 'Coordinate Geometry of Circle: Tangents', objectives: ['Find the equation of a tangent to a circle at a given point', 'Find the equation of a normal to a circle at a given point', 'Locate points of intersection between lines and circles'] },
                { week: 'Week 9', topic: 'Integration: Introduction', objectives: ['Define integration as the reverse of differentiation', 'Integrate simple polynomial functions', 'Apply integration to solve coordinate curve equations'] },
                { week: 'Week 10', topic: 'Revision & Mock Exams', objectives: ['Review matrices, vectors, circles, and integration basics', 'Execute mock exam booklets under timed settings', 'Evaluate final term grade boundaries'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Calculus: Limits & Continuity', objectives: ['Understand the concept of limits of algebraic functions', 'Evaluate limits of functions at specific points', 'Explain the condition for continuity of curves'] },
                { week: 'Week 2', topic: 'Differentiation from First Principles', objectives: ['Define rate of change and the derivative', 'Differentiate simple functions (y = x^2, y = x^3) from first principles', 'Understand the geometric meaning of derivative as tangent gradient'] },
                { week: 'Week 3', topic: 'Differentiation Rules', objectives: ['Differentiate polynomials using the power rule', 'Differentiate functions using the product rule', 'Differentiate functions using the quotient rule'] },
                { week: 'Week 4', topic: 'Differentiation: Chain Rule', objectives: ['State and apply the chain rule (derivative of function of a function)', 'Perform implicit differentiation on coordinate equations', 'Differentiate trigonometric functions (sin x, cos x)'] },
                { week: 'Week 5', topic: 'Calculus: Rates of Change', objectives: ['Apply differentiation to calculate velocity and acceleration from distance functions', 'Solve rates of change problems in chemistry and physics', 'Understand simple derivatives in finance'] },
                { week: 'Week 6', topic: 'Calculus: Turning Points', objectives: ['Identify stationary points on coordinate curves', 'Find local maximum and local minimum values', 'Solve optimization word problems (e.g. maximum area)'] },
                { week: 'Week 7', topic: 'Integration: Definite Integrals', objectives: ['Calculate definite integrals with boundary limits', 'Calculate the area under a curve bounded by x-axis', 'Apply definite integrals to evaluate volumes of revolution'] },
                { week: 'Week 8', topic: 'Integration: Applications', objectives: ['Solve velocity and distance equations using integration', 'Evaluate compound areas between two intersecting curves', 'Understand integrals in physics work calculations'] },
                { week: 'Week 9', topic: 'Calculus Revision & Practice', objectives: ['Review all differentiation and integration rules', 'Resolve past WAEC/NECO calculus questions', 'Simulate mock math papers'] },
                { week: 'Week 10', topic: 'Revision & Mock Exams', objectives: ['Review all algebra, statistics, geometry, and calculus taught in SS 3', 'Practice time management during WAEC math mock tests', 'Complete final mock evaluations'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Revision: Number Base & Logarithms', objectives: ['Review binary arithmetic, base equations, and log calculations', 'Solve past exam questions on number bases', 'Clarify fractional log calculations'] },
                { week: 'Week 2', topic: 'Revision: Algebra & Equations', objectives: ['Review simultaneous equations, quadratics, indices, and surds', 'Practice quick-solving factorization shortcuts', 'Review matrix operations'] },
                { week: 'Week 3', topic: 'Revision: Geometry & Trigonometry', objectives: ['Review circle geometry theorems, bearings, and height problems', 'Review trig graph configurations', 'Practice standard geometry proof constructs'] },
                { week: 'Week 4', topic: 'Revision: Calculus & Statistics', objectives: ['Review limits, derivatives, integrals, and cumulative charts', 'Solve grouped standard deviations quickly', 'Clarify calculus optimization graphs'] },
                { week: 'Week 5', topic: 'WAEC/NECO Examination Practice', objectives: ['Practice WAEC and NECO multiple-choice answer sheets', 'Practice structured theory writing constraints', 'Analyze common mistakes in past student papers'] },
                { week: 'Week 6', topic: 'WAEC/NECO Examination Practice', objectives: ['Execute full-length practice tests under exam conditions', 'Review answers with marking guides', 'Polish speed solving tips'] },
                { week: 'Week 7', topic: 'WAEC/NECO Final Examinations', objectives: ['Sit for the national mathematics paper 1 (multiple-choice)', 'Sit for the national mathematics paper 2 (structured theory)', 'Confirm exam protocol compliance'] },
                { week: 'Week 8', topic: 'WAEC/NECO Final Examinations', objectives: ['Complete remaining science and commercial papers', 'Monitor national exam updates', 'Complete mathematics syllabus objectives'] },
                { week: 'Week 9', topic: 'WAEC/NECO Final Examinations', objectives: ['Complete practical assessments and languages', 'Assess personal mastery gains', 'Celebrate mathematics achievement milestones'] },
                { week: 'Week 10', topic: 'WAEC/NECO Final Examinations', objectives: ['Conclude all national examinations', 'Conduct course feedback surveys', 'Transition to higher educational paths'] }
            ]
        }
    },
    'Basic Science': {
        'JSS 1': {
            'Term 1': [
                { week: 'Week 1', topic: 'Introduction to Basic Science', objectives: ['Define Basic Science and explain its importance', 'State the steps in the scientific method', 'Identify safety rules in a science laboratory'] },
                { week: 'Week 2', topic: 'Scientific Method & Apparatus', objectives: ['Demonstrate the use of simple science laboratory apparatus', 'Write simple science laboratory reports following scientific guidelines', 'Practice basic measuring techniques'] },
                { week: 'Week 3', topic: 'Living and Non-Living Things', objectives: ['State the characteristics of living things (MR NIGER D)', 'Differentiate between living and non-living things', 'Classify common objects into living and non-living categories'] },
                { week: 'Week 4', topic: 'Classification of Living Things', objectives: ['Classify living things into plants and animals', 'Identify differences between plants and animals', 'Differentiate between flowering and non-flowering plants'] },
                { week: 'Week 5', topic: 'Family Health: Personal Hygiene', objectives: ['Explain personal hygiene and identify materials used for cleanliness', 'Explain the importance of teeth, hair, and skin care', 'Demonstrate correct handwashing steps'] },
                { week: 'Week 6', topic: 'Family Health: Sanitation', objectives: ['State methods of refuse and sewage disposal in the community', 'Describe the relationship between poor sanitation and disease spread', 'Identify components of a healthy sanitary household'] },
                { week: 'Week 7', topic: 'Human Development: Puberty', objectives: ['Define puberty and state age ranges for boys and girls', 'List physical changes that occur during puberty in males and females', 'Discuss emotional and psychological changes during adolescence'] },
                { week: 'Week 8', topic: 'Reproductive Health: Hygiene', objectives: ['Describe hygiene practices during menstruation', 'Understand reproductive organ care and health issues', 'Discuss societal myths and facts about menstruation'] },
                { week: 'Week 9', topic: 'Disease Prevention: Immunization', objectives: ['Define immunization and list major vaccines', 'Explain the concept of community immunity', 'State immunization schedules for infants'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review all introductory science, living things, and health topics', 'Review laboratory guidelines', 'Complete the end-of-term basic science examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Matter: States and Properties', objectives: ['Define matter and identify the three states of matter', 'Explain the physical properties of solids, liquids, and gases', 'Explain chemical properties of common substances'] },
                { week: 'Week 2', topic: 'Matter: State Changes', objectives: ['Describe the processes of melting, freezing, evaporation, condensation, and sublimation', 'Show state change points (boiling/freezing points) experimentally', 'Explain how heat absorption causes state shifts'] },
                { week: 'Week 3', topic: 'Metals and Non-Metals', objectives: ['Distinguish between metals and non-metals based on properties', 'Identify common metals used in everyday construction', 'Explain the concept of alloys'] },
                { week: 'Week 4', topic: 'Energy: Forms and Sources', objectives: ['Define energy, work, and power', 'Identify forms of energy (chemical, electrical, light, heat, sound)', 'Classify energy sources into renewable and non-renewable categories'] },
                { week: 'Week 5', topic: 'Energy Conservation', objectives: ['Explain the law of conservation of energy', 'Describe energy transformation processes (e.g., chemical to electrical)', 'Investigate energy efficiency in home appliances'] },
                { week: 'Week 6', topic: 'Environmental Pollution: Introduction', objectives: ['Define environmental pollution and list its major types', 'State the causes and effects of air pollution', 'Investigate smoke emission hazards'] },
                { week: 'Week 7', topic: 'Water Pollution', objectives: ['State the causes and effects of water pollution', 'Investigate the impact of water pollution on aquatic life', 'List methods of water purification'] },
                { week: 'Week 8', topic: 'Land Pollution', objectives: ['State the causes and effects of land pollution', 'Discuss non-biodegradable waste hazards (e.g., plastics)', 'Suggest community land protection measures'] },
                { week: 'Week 9', topic: 'Pollution Control', objectives: ['List methods of controlling environmental pollution', 'Explain the 3 Rs: Reduce, Reuse, and Recycle', 'Discuss environmental protection agencies\' roles in Nigeria'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review matter, energy, and environmental pollution topics', 'Practice matching terms and short definitions', 'Complete the end-of-term basic science examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Force', objectives: ['Define force and identify its types (contact and non-contact)', 'Provide everyday examples of forces in action', 'Measure force using a spring balance'] },
                { week: 'Week 2', topic: 'Friction: Introduction', objectives: ['Explain the concept of friction', 'Identify advantages and disadvantages of friction in daily activities', 'Demonstrate friction variance on different surfaces'] },
                { week: 'Week 3', topic: 'Friction Control', objectives: ['State methods of reducing friction (lubricants, bearings)', 'State methods of increasing friction (treads, spikes)', 'Explain how friction impacts mechanical efficiency'] },
                { week: 'Week 4', topic: 'Gravity', objectives: ['Define gravity and gravitational pull', 'Explain how gravity holds objects on the earth\'s surface', 'Investigate falling speeds in air vs. vacuum'] },
                { week: 'Week 5', topic: 'The Solar System', objectives: ['Describe the solar system and name the nine planets in order', 'Differentiate between planets, stars, and satellites', 'Investigate the size scale of planets relative to the sun'] },
                { week: 'Week 6', topic: 'Earth Rotation', objectives: ['Explain the rotation of the earth on its axis', 'Demonstrate how day and night occur using a globe and light source', 'Understand timezone differences'] },
                { week: 'Week 7', topic: 'Earth Revolution', objectives: ['Explain the revolution of the earth around the sun', 'Describe how seasons occur due to earth\'s tilt', 'Differentiate between rotation and revolution'] },
                { week: 'Week 8', topic: 'Space Travel: Basics', objectives: ['Define space travel and state its purpose', 'Identify artificial satellites and their uses in communication', 'Describe the conditions astronauts face in space'] },
                { week: 'Week 9', topic: 'Space Exploration Benefits', objectives: ['Describe the benefits of space exploration to mankind', 'Identify the hazards and challenges of space travel', 'Discuss international space agencies and programs'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review force, friction, gravity, solar system, and space travel', 'Draw and label simple planetary orbits', 'Complete the end-of-term basic science examination'] }
            ]
        },
        'JSS 2': {
            'Term 1': [
                { week: 'Week 1', topic: 'Family Health: Nutrition', objectives: ['Define a balanced diet and list the six food classes', 'State the functions of carbohydrates and proteins', 'Identify food sources rich in each nutrient group'] },
                { week: 'Week 2', topic: 'Nutrition: Fats & Vitamins', objectives: ['State the functions of fats, vitamins, and minerals', 'Explain the role of dietary fiber and water in digestion', 'Test for simple nutrients in food samples'] },
                { week: 'Week 3', topic: 'Malnutrition', objectives: ['Identify diseases associated with malnutrition (kwashiorkor, rickets, scurvy)', 'Suggest menu corrections for malnourished individuals', 'Discuss nutritional deficiency solutions'] },
                { week: 'Week 4', topic: 'First Aid Procedures', objectives: ['Explain the meaning and objectives of First Aid', 'List the contents of a standard First Aid box', 'Demonstrate safe first aid protocols'] },
                { week: 'Week 5', topic: 'Emergency Interventions', objectives: ['Demonstrate how to treat severe bleeding and wounds', 'Demonstrate steps for treating snake bites and poisoning', 'Demonstrate simple burns and scalds care'] },
                { week: 'Week 6', topic: 'CPR and Fractures', objectives: ['Demonstrate procedures for artificial respiration (CPR)', 'Demonstrate how to stabilize bone fractures using splints', 'Outline safety guidelines in carrying injured victims'] },
                { week: 'Week 7', topic: 'Kinetic Theory of Matter', objectives: ['State the assumptions of the kinetic theory of matter', 'Explain the behavior of particles in solids, liquids, and gases', 'Demonstrate states of matter density variations'] },
                { week: 'Week 8', topic: 'Particles in Motion', objectives: ['Investigate diffusion in gases and liquids', 'Explain Brownian motion in scientific terms', 'State factors affecting the rate of diffusion'] },
                { week: 'Week 9', topic: 'Evaporation & Boiling', objectives: ['Differentiate between evaporation and boiling', 'State factors affecting evaporation rate', 'Explain how heat absorption drives particle movement'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review nutrition, first aid, kinetic theory, and states of matter', 'Practice labeling medical and physical drawings', 'Complete the end-of-term basic science examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Work, Energy & Power', objectives: ['State mathematical formulas for Work, Potential Energy, Kinetic Energy, and Power', 'Calculate work done and power expended in simple exercises', 'Understand energy efficiency in mechanics'] },
                { week: 'Week 2', topic: 'Simple Machines', objectives: ['Define a machine and identify types of simple machines', 'Identify pulleys, gears, wheels, and axles in daily tools', 'Differentiate between simple and complex machines'] },
                { week: 'Week 3', topic: 'Mechanical Advantage', objectives: ['Explain mechanical advantage (MA) and velocity ratio (VR)', 'Calculate mechanical advantage and efficiency of simple machines', 'State reasons why machine efficiency is never 100%'] },
                { week: 'Week 4', topic: 'Levers', objectives: ['Define levers and identify components: effort, load, fulcrum', 'Classify levers into first, second, and third-class categories', 'Provide examples of levers in daily home tools'] },
                { week: 'Week 5', topic: 'Crude Oil & Petroleum', objectives: ['Explain the origin and formation of crude oil and natural gas', 'State the economic importance of crude oil to Nigeria', 'Outline oil exploration and drilling steps'] },
                { week: 'Week 6', topic: 'Fractional Distillation', objectives: ['Explain fractional distillation process of crude oil', 'Differentiate fractions based on boiling point ranges', 'Sketch a simple fractional distillation column model'] },
                { week: 'Week 7', topic: 'Petroleum Fractions Uses', objectives: ['Identify major petroleum fractions (petrol, diesel, kerosene, paraffin, bitumen)', 'State uses of each petroleum fraction in transportation and industry', 'Discuss fuel combustion hazards'] },
                { week: 'Week 8', topic: 'Petrochemicals', objectives: ['Identify petrochemical products (plastics, solvents, synthetic fibers, detergents)', 'Discuss how petrochemicals are manufactured', 'Outline plastic recycling advantages'] },
                { week: 'Week 9', topic: 'Environmental Impact of Petroleum', objectives: ['Discuss causes and consequences of oil spillage', 'Discuss causes and consequences of gas flaring', 'Outline remediation methods for oil-polluted soils and waters'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review machines, energy calculations, crude oil, and petrochemicals', 'Solve mechanical efficiency equations', 'Complete the end-of-term basic science examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Skeletal System', objectives: ['Identify bones of the human skeleton', 'List the functions of the human skeleton', 'Differentiate between axial and appendicular skeletons'] },
                { week: 'Week 2', topic: 'Joints and Muscles', objectives: ['Identify types of joints (hinge, ball-and-socket, pivot, gliding)', 'Explain the role of muscles, ligaments, and tendons in movement', 'Discuss skeletal disorders like arthritis and rickets'] },
                { week: 'Week 3', topic: 'Digestive System: Organs', objectives: ['Identify organs of the human digestive tract', 'Describe structures of the stomach and small intestines', 'Sketch the human digestive system accurately'] },
                { week: 'Week 4', topic: 'Digestive Process', objectives: ['State digestion steps: ingestion, digestion, absorption, assimilation, and egestion', 'Explain the role of enzymes in chemical digestion', 'Investigate food absorption in the villi'] },
                { week: 'Week 5', topic: 'Male Reproductive System', objectives: ['Identify organs of the male reproductive system', 'State the functions of male reproductive organs', 'Sketch and label sperm cells'] },
                { week: 'Week 6', topic: 'Female Reproductive System', objectives: ['Identify organs of the female reproductive system', 'State the functions of female reproductive organs', 'Sketch and label ova (egg cells)'] },
                { week: 'Week 7', topic: 'Fertilization & Gestation', objectives: ['Explain the process of fertilization and zygote formation', 'Explain implantation and placenta roles', 'Trace stages of gestation in mammalian pregnancy'] },
                { week: 'Week 8', topic: 'Fetal Development & Birth', objectives: ['Describe fetal development weeks step-by-step', 'Explain the biological stages of childbirth', 'Discuss post-natal care principles'] },
                { week: 'Week 9', topic: 'Parental Health Care', objectives: ['Discuss the nutritional and healthcare needs of pregnant women', 'Explain the importance of breastfeeding and infant immunization', 'Identify family planning counseling options'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review skeletal, digestive, and reproductive system topics', 'Review anatomical drawings', 'Complete the end-of-term basic science examination'] }
            ]
        },
        'JSS 3': {
            'Term 1': [
                { week: 'Week 1', topic: 'Family Health: Drug Abuse', objectives: ['Define drug abuse and identify commonly abused drugs', 'Distinguish between prescription drug misuse and illicit drug abuse', 'Identify signs of drug abuse in adolescents'] },
                { week: 'Week 2', topic: 'Consequences of Drug Abuse', objectives: ['State the social and health consequences of drug abuse', 'State the economic impacts of drug addiction on families', 'Explain how drug abuse impairs central nervous system performance'] },
                { week: 'Week 3', topic: 'Drug Control & Prevention', objectives: ['Outline drug abuse prevention methods', 'State roles of regulatory agencies in Nigeria (NDLEA, NAFDAC)', 'Discuss treatment and rehabilitation pathways for drug addicts'] },
                { week: 'Week 4', topic: 'Resources from Living Things: Plants', objectives: ['Identify plant resources (wood, fiber, rubber, latex, medicine)', 'State locations of major timber forest zones in Nigeria', 'Discuss economic benefits of wood processing'] },
                { week: 'Week 5', topic: 'Resources from Living Things: Animals', objectives: ['Identify animal resources (meat, hides, leather, honey, dairy)', 'State the economic importance of livestock farming in Nigeria', 'Suggest methods of preserving animal resource quality'] },
                { week: 'Week 6', topic: 'Resources from Non-Living Things', objectives: ['Identify major mineral resources in Nigeria (coal, petroleum, gold, tin)', 'State the economic importance of mineral extraction', 'Outline mining safety regulations'] },
                { week: 'Week 7', topic: 'Mineral Locations in Nigeria', objectives: ['Locate mineral deposits in Nigeria on a geographic map', 'Identify states producing coal, crude oil, and iron ore', 'Discuss mineral exploration rights'] },
                { week: 'Week 8', topic: 'Non-Living Resources Value', objectives: ['Detail the financial and industrial contributions of mining', 'Discuss ecological hazards of open-cast mining', 'Outline soil reclamation methods'] },
                { week: 'Week 9', topic: 'Environmental Protection', objectives: ['Identify causes of flooding, soil erosion, and desertification', 'Discuss control measures for environmental degradation', 'Outline the role of afforestation in environmental protection'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review drug abuse, biological resources, minerals, and environmental protection', 'Complete map reading test revisions', 'Complete the end-of-term basic science examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Light Energy: Propagation', objectives: ['Describe the propagation of light in straight lines', 'Demonstrate shadows and eclipse formations', 'Construct a simple pinhole camera experimentally'] },
                { week: 'Week 2', topic: 'Reflection of Light', objectives: ['State the laws of reflection of light', 'Differentiate between regular and diffuse reflection', 'Locate images in plane mirrors geometrically'] },
                { week: 'Week 3', topic: 'Refraction & Lenses', objectives: ['Explain refraction of light and refractive indexes', 'Distinguish between convex (converging) and concave (diverging) lenses', 'Show real and virtual images produced by lenses'] },
                { week: 'Week 4', topic: 'Magnetism', objectives: ['Identify magnetic poles and describe laws of attraction and repulsion', 'Differentiate between permanent and temporary magnets', 'Map magnetic field lines using compasses'] },
                { week: 'Week 5', topic: 'Static Electricity', objectives: ['Explain static electricity and charge generations', 'Describe the gold-leaf electroscope and its uses', 'Explain lighting strikes and lightning conductors'] },
                { week: 'Week 6', topic: 'Current Electricity', objectives: ['Distinguish between static electricity and current electricity', 'Define conductors, insulators, and semiconductors', 'State current, voltage, and resistance units'] },
                { week: 'Week 7', topic: 'Series & Parallel Circuits', objectives: ['Construct series and parallel electrical circuits', 'Calculate resistance in series and parallel connections', 'Demonstrate voltage splits in circuits'] },
                { week: 'Week 8', topic: 'Atomic Structure', objectives: ['State sub-atomic particles (protons, neutrons, electrons)', 'Draw simple Bohr models of atoms (hydrogen, carbon)', 'Differentiate between atomic number and mass number'] },
                { week: 'Week 9', topic: 'Electronics Components', objectives: ['Identify resistors, capacitors, diodes, and transistors', 'Explain active and passive electronic components', 'Construct simple LED lighting circuits'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review light, magnetism, electricity, atoms, and electronics', 'Practice solving circuit calculations', 'Complete the end-of-term basic science examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Respiration & Breathing', objectives: ['Differentiate between breathing and respiration', 'Sketch respiratory systems of fish, insects, and mammals', 'Investigate carbon dioxide output in human breathing'] },
                { week: 'Week 2', topic: 'Cellular Respiration', objectives: ['Define cellular respiration as energy release', 'Write aerobic and anaerobic respiration equations', 'Identify the role of mitochondria and ATP in cell energy'] },
                { week: 'Week 3', topic: 'Excretory System', objectives: ['Identify excretory organs (kidneys, lungs, skin, liver)', 'State waste products excreted by each organ', 'Sketch and label kidney nephron units'] },
                { week: 'Week 4', topic: 'Genetics and Heredity', objectives: ['Define genetics, genes, chromosomes, and heredity', 'State Gregor Mendel\'s role in biology history', 'Distinguish between genotypes and phenotypes'] },
                { week: 'Week 5', topic: 'Inheritable & Non-Inheritable Traits', objectives: ['Identify inheritable traits (height, blood group, fingerprints)', 'Explain the concept of variation in species', 'Differentiate between continuous and discontinuous variation'] },
                { week: 'Week 6', topic: 'Acquired Characteristics', objectives: ['Define acquired or non-inheritable traits', 'Investigate environmental impacts on trait development', 'Explain the difference between nature and nurture'] },
                { week: 'Week 7', topic: 'Family Pedigree & Blood Groups', objectives: ['Understand Rhesus factor compatibility', 'Discuss genetic counseling significance (sickle-cell anemia)', 'Map a simple family trait tree'] },
                { week: 'Week 8', topic: 'Evolutionary Theories', objectives: ['Explain basic concepts of evolution', 'Describe physiological and morphological adaptations in organisms', 'Outline fossil records value'] },
                { week: 'Week 9', topic: 'General Revisions', objectives: ['Review JSS 1 to JSS 3 Basic Science syllabus topics', 'Conduct comprehensive speed practice testing', 'Execute mock exam workshops'] },
                { week: 'Week 10', topic: 'JSSCE Final Examinations', objectives: ['Sit for the Junior Secondary Certificate Examinations', 'Complete theory and practical answer sheets successfully', 'Evaluate final basic science mastery levels'] }
            ]
        },
        'SS 1': {
            'Term 1': [
                { week: 'Week 1', topic: 'Biology & Scientific Method', objectives: ['Describe biology as the study of life and state its branches', 'Apply the scientific method in planning simple biological experiments', 'Identify laboratory tools and their safety rules'] },
                { week: 'Week 2', topic: 'Laboratory Tools & Microscope', objectives: ['Identify parts of the light microscope', 'Calculate microscope magnification powers', 'Prepare simple slides of plant and animal tissue'] },
                { week: 'Week 3', topic: 'Classification: Nomenclature', objectives: ['Explain the binomial system of nomenclature developed by Linnaeus', 'State the seven levels of taxonomic hierarchy', 'Identify botanical names of common local plants and crops'] },
                { week: 'Week 4', topic: 'Kingdom Monera & Protista', objectives: ['Classify organisms into the five kingdoms', 'Describe characteristics of bacteria (Kingdom Monera)', 'Describe characteristics of Amoeba and Paramecium (Kingdom Protista)'] },
                { week: 'Week 5', topic: 'Kingdom Fungi & Plantae', objectives: ['Describe characteristics of yeasts and molds (Kingdom Fungi)', 'Classify plants into Thallophytes, Bryophytes, Pteridophytes, and Spermatophytes', 'State differences between monocots and dicots'] },
                { week: 'Week 6', topic: 'Kingdom Animalia', objectives: ['Distinguish between invertebrates and vertebrates', 'Detail characteristics of Arthropods (insects, arachnids)', 'Classify vertebrates into Pisces, Amphibia, Reptilia, Aves, and Mammalia'] },
                { week: 'Week 7', topic: 'Cell Structure & Organelles', objectives: ['Identify cell organelles under light and electron microscopes', 'State functions of nucleus, mitochondria, chloroplasts, Golgi body', 'Understand cell theory assumptions'] },
                { week: 'Week 8', topic: 'Plant and Animal Cells', objectives: ['Differentiate between plant and animal cell structures', 'Sketch high-definition models of plant and animal cells', 'Explain cell specialization in tissue formation'] },
                { week: 'Week 9', topic: 'Cell Properties: Transport', objectives: ['Explain the process and equations of Diffusion', 'Explain the process and equations of Osmosis', 'Explain the process and equations of Active Transport in cells'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review scientific method, kingdoms, cell structure, and transport', 'Resolve microscope drawing revisions', 'Complete the end-of-term biology examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Photosynthesis: Equation & Stages', objectives: ['Write the chemical equation for photosynthesis', 'Explain the light-dependent stage of photosynthesis', 'Describe the light-independent (dark) stage of photosynthesis'], dbTopicMatch: 'photosynthesis' },
                { week: 'Week 2', topic: 'Factors of Photosynthesis', objectives: ['Explain how light intensity affects photosynthesis rate', 'Explain how carbon dioxide concentration affects photosynthesis', 'Explain how temperature affects photosynthesis rate'] },
                { week: 'Week 3', topic: 'Plant Mineral Nutrition', objectives: ['Classify plant nutrients into macroelements (N, P, K) and microelements', 'Identify symptoms of nutrient deficiencies in plants', 'Discuss commercial fertilizer formulations'] },
                { week: 'Week 4', topic: 'Cellular Respiration: Glycolysis', objectives: ['Distinguish between aerobic and anaerobic cellular respiration', 'Describe the process of Glycolysis in cell cytoplasm', 'Describe the Citric Acid Cycle (Krebs cycle) in mitochondria'], dbTopicMatch: 'cellular respiration' },
                { week: 'Week 5', topic: 'Anaerobic Respiration', objectives: ['Explain anaerobic respiration in yeast (fermentation)', 'Explain anaerobic respiration in muscles (lactic acid accumulation)', 'State industrial applications of fermentation'] },
                { week: 'Week 6', topic: 'Respiratory Mechanisms', objectives: ['Describe respiratory organs in fish (gills), insects (trachea), and mammals (lungs)', 'Explain the mechanisms of inhalation and exhalation in humans', 'Differentiate between internal and external respiration'] },
                { week: 'Week 7', topic: 'Excretion: Unicellular & Lower Organisms', objectives: ['Define excretion and its biological importance', 'Describe contractile vacuole excretion in amoeba', 'Describe flame cell and nephridia excretion in lower worms'] },
                { week: 'Week 8', topic: 'Excretory Waste Products', objectives: ['List excretory waste products of plants (tannins, latex, oxygen)', 'List excretory waste products of animals (ammonia, urea, carbon dioxide)', 'State the toxic impacts of waste accumulation in cells'] },
                { week: 'Week 9', topic: 'Excretion: Homeostatic Controls', objectives: ['Describe excretory systems coordination with the endocrine system', 'Understand skin structure as a regulatory instrument', 'Explain lung CO2 excretion processes'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review photosynthesis, respiration, and excretory systems', 'Practice chemical balance equations', 'Complete the end-of-term biology examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Basic Ecology: Biomes & Systems', objectives: ['Define ecosystem, biosphere, biome, population, and community', 'Identify major terrestrial and aquatic biomes in Nigeria', 'Differentiate between biotic and abiotic factors of an ecosystem'] },
                { week: 'Week 2', topic: 'Biotic and Abiotic Interactions', objectives: ['Explain how temperature, rainfall, and pH shape species distribution', 'Define ecological niche and microhabitats', 'Conduct simple school garden ecological mappings'] },
                { week: 'Week 3', topic: 'Food Chains & Food Webs', objectives: ['Construct food chains for terrestrial and aquatic ecosystems', 'Construct complex food webs', 'Identify producers, consumers, and decomposers'] },
                { week: 'Week 4', topic: 'Trophic Levels & Energy Flow', objectives: ['Explain energy transfer efficiency between trophic levels', 'Draw pyramids of numbers, biomass, and energy', 'State the role of decomposers in nutrient recycling'] },
                { week: 'Week 5', topic: 'Biogeochemical Cycles: Carbon', objectives: ['Sketch the carbon cycle in nature', 'Discuss carbon cycle balance factors (photosynthesis vs. burning)', 'Discuss industrial greenhouse gas emissions and global warming'] },
                { week: 'Week 6', topic: 'Biogeochemical Cycles: Nitrogen', objectives: ['Sketch the nitrogen cycle in nature', 'Detail nitrogen-fixing bacteria, nitrifying bacteria, and denitrifying bacteria', 'State nitrogen cycle importance in farming'] },
                { week: 'Week 7', topic: 'Ecological Succession', objectives: ['Define ecological succession and pioneer communities', 'Differentiate between primary and secondary succession', 'Identify climax communities in local biomes'] },
                { week: 'Week 8', topic: 'Ecological Adaptations', objectives: ['Describe morphological adaptations of desert plants (xerophytes)', 'Describe morphological adaptations of aquatic plants (hydrophytes)', 'Describe animal survival adaptations (camouflage, mimicry)'] },
                { week: 'Week 9', topic: 'Conservation of Resources', objectives: ['State the importance of forest, water, soil, and wildlife conservation', 'Discuss environmental conservation laws in Nigeria', 'Outline endangered species protection measures'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review ecology, food webs, biogeochemical cycles, and adaptations', 'Solve trophic level math calculations', 'Complete the end-of-term biology examination'] }
            ]
        },
        'SS 2': {
            'Term 1': [
                { week: 'Week 1', topic: 'Digestive Systems: Dentition', objectives: ['Identify teeth types and dental formulas in omnivores, herbivores, and carnivores', 'Differentiate dental adaptations in mammals', 'State functions of teeth structures'] },
                { week: 'Week 2', topic: 'Digestive Systems: Human Organs', objectives: ['State functions of stomach, duodenum, liver, and pancreas in digestion', 'Explain physical vs. chemical digestion processes', 'Sketch the human digestive tract'] },
                { week: 'Week 3', topic: 'Chemical Digestion & Enzymes', objectives: ['Explain the action of salivary amylase, pepsin, trypsin, lipase', 'Detail pancreatic juice and bile functions', 'Test for simple digestion conversions experimentally'] },
                { week: 'Week 4', topic: 'Transport Systems: Vascular Networks', objectives: ['Compare passive transport vs. vascular transport systems in plants and animals', 'Outline surface area to volume ratio limits in transport', 'Describe transport systems in insects'] },
                { week: 'Week 5', topic: 'Blood Composition', objectives: ['Identify cellular components of blood (red cells, white cells, platelets)', 'State functions of plasma components (proteins, salts, waste)', 'Understand blood clot mechanisms'] },
                { week: 'Week 6', topic: 'The Mammalian Heart', objectives: ['Describe the internal structure of the mammalian heart', 'Trace the path of double circulation in mammals', 'Calculate pulse rates and understand blood pressure anomalies'] },
                { week: 'Week 7', topic: 'Blood Transfusion & Rhesus', objectives: ['Classify human blood groups (A, B, AB, O)', 'Explain Rhesus factor compatibility', 'Analyze blood transfusion matching charts'] },
                { week: 'Week 8', topic: 'Plant Transport: Xylem & Phloem', objectives: ['State xylem and phloem locations in plant stems', 'Explain root pressure and cohesive force theories', 'Detail translocation of manufactured food'] },
                { week: 'Week 9', topic: 'Transpiration', objectives: ['Explain the mechanism of transpiration', 'State factors affecting transpiration rates', 'Investigate transpiration using potometers'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review dentition, human digestion, transport, blood, and plant transpiration', 'Resolve anatomical sketching exercises', 'Complete the end-of-term biology examination'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Excretion: Mammalian Kidneys', objectives: ['Describe the anatomical structure of mammalian kidneys', 'Identify nephron structures (Bowman\'s capsule, Henle\'s loop)', 'State major waste components of urine'] },
                { week: 'Week 2', topic: 'Urine Formation', objectives: ['Explain ultra-filtration processes in glomerulus', 'Explain selective reabsorption in proximal and distal tubules', 'Trace the urine pathway from kidney to bladder'] },
                { week: 'Week 3', topic: 'Osmoregulation', objectives: ['Explain the kidney\'s role in water and salt balance', 'Detail ADH (antidiuretic hormone) control loops', 'Investigate kidney dialysis and failure symptoms'] },
                { week: 'Week 4', topic: 'Nervous System: CNS vs. PNS', objectives: ['Describe divisions of the nervous system', 'Identify structures of sensory, motor, and relay neurons', 'State functions of myelin sheath and synapses'] },
                { week: 'Week 5', topic: 'The Human Brain', objectives: ['Identify parts of the brain (cerebrum, cerebellum, medulla oblongata)', 'State functions of forebrain, midbrain, and hindbrain sections', 'Sketch the human brain'] },
                { week: 'Week 6', topic: 'Refex Action', objectives: ['Explain the pathway of a simple reflex arc', 'Differentiate between voluntary actions and reflex actions', 'Discuss conditioned reflex examples (Ivan Pavlov\'s experiments)'] },
                { week: 'Week 7', topic: 'Sense Organs: The Eye', objectives: ['Describe the internal structure of the human eye', 'Explain the mechanism of light focus (accommodation)', 'Discuss eye defects (myopia, hypermetropia, astigmatism) and corrections'] },
                { week: 'Week 8', topic: 'Sense Organs: The Ear', objectives: ['Describe the anatomical divisions of the human ear (outer, middle, inner)', 'Explain the mechanisms of hearing', 'Explain the role of semicircular canals in body balance'] },
                { week: 'Week 9', topic: 'Sense of Taste & Smell', objectives: ['Identify tongue taste zones (sweet, sour, bitter, salty)', 'Explain olfactory receptor pathways in smell sensations', 'Investigate sensory coordination'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review kidneys, urine, nervous system, brain, eye, and ear anatomy', 'Label complex sensory systems', 'Complete the end-of-term biology examination'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Endocrine System', objectives: ['Identify locations of pituitary, thyroid, adrenal, pancreas, and gonads glands', 'State differences between endocrine (ductless) and exocrine glands', 'Define hormones and state chemical properties'] },
                { week: 'Week 2', topic: 'Hormones Functions', objectives: ['State functions of adrenaline, insulin, thyroxine, testosterone, estrogen', 'Explain feedback control mechanisms in hormone secretions', 'Compare nervous coordination vs. hormonal coordination speed'] },
                { week: 'Week 3', topic: 'Hormonal Defects', objectives: ['State consequences of pituitary hypersecretion (gigantism) and hyposecretion', 'State consequences of thyroid defects (goiter, cretinism)', 'State consequences of pancreas defects (diabetes mellitus)'] },
                { week: 'Week 4', topic: 'Plant Hormones', objectives: ['Identify plant hormones (auxins, gibberellins, cytokinins, abscisic acid)', 'Explain the role of auxins in phototropism and geotropism', 'State synthetic plant hormones uses in commercial farming'] },
                { week: 'Week 5', topic: 'Mammalian Reproductive System', objectives: ['Identify male reproductive organs in mammals', 'Identify female reproductive organs in mammals', 'Sketch and label gamete structures'] },
                { week: 'Week 6', topic: 'Gametogenesis', objectives: ['Explain spermatogenesis stages in testes tubules', 'Explain oogenesis stages in ovaries follicles', 'Differentiate between mitosis and meiosis in gamete formation'] },
                { week: 'Week 7', topic: 'The Menstrual Cycle', objectives: ['Trace the hormonal phases of the menstrual cycle', 'Detail roles of estrogen, progesterone, LH, and FSH', 'Discuss ovulation calculation methods and biological variations'] },
                { week: 'Week 8', topic: 'Pregnancy and Birth', objectives: ['Explain fertilization processes in fallopian tubes', 'Explain implantation in uterine walls', 'Trace placenta and umbilical cord nutrient roles'] },
                { week: 'Week 9', topic: 'Birth Control & Planning', objectives: ['Identify barrier, hormonal, chemical, and surgical contraceptive methods', 'Discuss benefits of family planning in community development', 'State sexually transmitted disease (STIs) protection measures'] },
                { week: 'Week 10', topic: 'Revision & Term Examination', objectives: ['Review endocrine glands, plant hormones, and reproduction systems', 'Practice labeling uterine structures', 'Complete the end-of-term biology examination'] }
            ]
        },
        'SS 3': {
            'Term 1': [
                { week: 'Week 1', topic: 'Basic Genetics', objectives: ['Define genetics, genes, chromatin, homozygous, heterozygous, alleles', 'State Gregor Mendel\'s laws of inheritance', 'State Mendelian genetic terms'] },
                { week: 'Week 2', topic: 'Monohybrid Crosses', objectives: ['Solve monohybrid cross problems using Punnett squares', 'Explain dominant and recessive phenotypes', 'Determine genotypic and phenotypic ratios (3:1, 1:2:1)'] },
                { week: 'Week 3', topic: 'Dihybrid Crosses', objectives: ['Solve dihybrid cross problems using Punnett squares', 'State Mendel\'s law of independent assortment', 'Determine genotypic and phenotypic ratios (9:3:3:1)'] },
                { week: 'Week 4', topic: 'Incomplete & Codominance', objectives: ['Explain incomplete dominance (e.g. Mirabilis jalapa crossing)', 'Explain codominance (e.g. human AB blood groups)', 'Solve blood group genetic inheritance problems'] },
                { week: 'Week 5', topic: 'Sex-Linked Inheritance', objectives: ['Identify human sex chromosomes (XX, XY)', 'Explain sex determination mechanism in fertilization', 'Solve crosses for hemophilia and color blindness'] },
                { week: 'Week 6', topic: 'Chromosomes Structures', objectives: ['Describe chromosome morphology: chromatids, centromeres', 'Explain gene linkage groups and crossing-over', 'Identify chromosomal aberrations (mutations)'] },
                { week: 'Week 7', topic: 'DNA and RNA Structures', objectives: ['Describe the double-helix structure of DNA proposed by Watson and Crick', 'State base pairing rules (adenine-thymine, cytosine-guanine)', 'Differentiate between DNA and RNA chemical compositions'] },
                { week: 'Week 8', topic: 'DNA Replication & Synthesis', objectives: ['Explain semi-conservative DNA replication mechanisms', 'Detail transcription of DNA to messenger RNA (mRNA)', 'Describe translation of mRNA to proteins in ribosomes'] },
                { week: 'Week 9', topic: 'Applications of Genetics', objectives: ['Discuss genetic engineering in hybrid crop developments', 'Discuss DNA fingerprinting in crime scene investigations', 'Explain advantages and concerns of cloning and GMOs'] },
                { week: 'Week 10', topic: 'Revision & Mock Exams', objectives: ['Review all genetics crosses, chromosomal structures, and gene synthesis', 'Resolve past WAEC genetic questions', 'Complete term mock evaluations'] }
            ],
            'Term 2': [
                { week: 'Week 1', topic: 'Variation in Species', objectives: ['Define variation and its ecological significance', 'Identify continuous variation examples (height, weight, skin color)', 'Plot normal distribution curves representing continuous data'] },
                { week: 'Week 2', topic: 'Discontinuous Variation', objectives: ['Identify discontinuous variation examples (blood group, tongue rolling)', 'Differentiate between continuous and discontinuous variation data', 'Explain how genetic recombination causes variation'] },
                { week: 'Week 3', topic: 'Morphological Adaptations', objectives: ['Define morphological adaptations in biomes', 'State plant structural adaptations to deserts (succulent stems, spines)', 'Detail animal adaptative shapes in tundra zones'] },
                { week: 'Week 4', topic: 'Physiological Adaptations', objectives: ['Define physiological adaptations in cells', 'Explain osmoprotectants in brackish water species', 'Detail snake venoms as chemical protective mechanisms'] },
                { week: 'Week 5', topic: 'Behavioral Adaptations', objectives: ['Define behavioral adaptations in animals', 'Explain seasonal bird migrations', 'Explain estivation and hibernation triggers'] },
                { week: 'Week 6', topic: 'Evolution: Lamarck\'s Theory', objectives: ['Explain Jean-Baptiste Lamarck\'s theory of inheritance of acquired traits', 'Discuss fallacies of Lamarckism', 'Detail use and disuse concepts'] },
                { week: 'Week 7', topic: 'Evolution: Darwin\'s Theory', objectives: ['Explain Charles Darwin\'s theory of natural selection', 'Discuss the concept of survival of the fittest', 'Contrast Darwinian evolution vs. Lamarckian evolution'] },
                { week: 'Week 8', topic: 'Evidence for Evolution', objectives: ['Detail fossil records and geological time scales', 'Explain comparative anatomy and vestigial organs (e.g. appendix)', 'Explain embryological evidence in vertebrates development'] },
                { week: 'Week 9', topic: 'Modern Speciation', objectives: ['Explain speciation and reproductive isolation mechanisms', 'Detail mutations roles in accelerating evolutionary variations', 'Discuss modern evolutionary synthesis'] },
                { week: 'Week 10', topic: 'Revision & Mock Exams', objectives: ['Review variation, adaptations, evolution, and fossil lines', 'Execute practice mock examinations', 'Evaluate grading limits'] }
            ],
            'Term 3': [
                { week: 'Week 1', topic: 'Public Health: Malaria & Cholera', objectives: ['Identify transmission and control methods of malaria (Plasmodium)', 'Identify transmission and control methods of cholera (Vibrio cholerae)', 'Detail mosquito vector control procedures'] },
                { week: 'Week 2', topic: 'Disease Vectors & Aerosols', objectives: ['Classify diseases into air-borne, water-borne, contact, and sexually transmitted', 'Explain how aerosols spread respiratory pathogens', 'Outline sanitation safeguards'] },
                { week: 'Week 3', topic: 'Epidemic Prevention: Vaccines', objectives: ['Explain the role of quarantine, vaccination, and sanitizers in epidemic control', 'Detail historical smallpox and polio eradication milestones', 'Outline community health policies'] },
                { week: 'Week 4', topic: 'Community Water Purification', objectives: ['State municipal water filtration steps', 'Describe chlorination, sedimentation, and distillation', 'Identify water quality parameters'] },
                { week: 'Week 5', topic: 'Health Organizations', objectives: ['State roles of WHO, UNICEF, Red Cross, and local agencies', 'Outline pandemic preparedness structures', 'Discuss healthcare access in rural areas'] },
                { week: 'Week 6', topic: 'General Revision: Physiology', objectives: ['Review kingdom classification, cell structures, and cell physiology', 'Resolve comprehensive speed test sheets', 'Polish scientific drawing requirements'] },
                { week: 'Week 7', topic: 'General Revision: Ecology & Genetics', objectives: ['Review carbon cycles, food chains, genetic crosses, and DNA synthesis', 'Clarify Mendelian exceptions', 'Review Ogive population charts'] },
                { week: 'Week 8', topic: 'Practical Specimen Analysis', objectives: ['Analyze biological specimens, structural setups, and sections under lenses', 'Identify key specimens features (adaptation, classification)', 'Outline microscope drawing standards'] },
                { week: 'Week 9', topic: 'WAEC/NECO Examination Practice', objectives: ['Execute full-length practice tests under exam conditions', 'Review answers with marking guides', 'Polish speed solving tips'] },
                { week: 'Week 10', topic: 'Final WAEC/NECO Examinations', objectives: ['Sit for the national biology paper 1 (multiple-choice)', 'Sit for the national biology paper 2 (structured theory)', 'Sit for the biology practical examination'] }
            ]
        }
    }
};

export default CURRICULUM_DATA;
